from typing import Optional
from pydantic import BaseModel, Field, model_validator, ConfigDict
from datetime import datetime

from .doctor import DoctorResponse


class CommentBase(BaseModel):
    """Base Comment schema with common attributes"""
    content: str = Field(..., description="Comment content", example="This appears to be a fracture in the distal radius.")
    is_ai_generated: bool = Field(False, description="Whether the comment was generated by AI")
    ai_model: Optional[str] = Field(None, description="AI model used to generate the comment", example="gemini-2.0-flash")


class CommentCreate(CommentBase):
    """Schema for creating a new comment"""
    image_id: Optional[int] = Field(None, description="ID of the image being commented on")
    study_instance_uid: Optional[str] = Field(
        None,
        description="StudyInstanceUID used to resolve the image if image_id is not provided",
    )
    series_instance_uid: Optional[str] = Field(
        None,
        description="SeriesInstanceUID used to resolve the image if image_id is not provided",
    )
    sop_instance_uid: Optional[str] = Field(
        None,
        description="SOPInstanceUID used to resolve the image if image_id is not provided",
    )

    @model_validator(mode="after")
    def validate_image_ref(self):
        image_id = self.image_id
        s = self.study_instance_uid
        r = self.series_instance_uid
        o = self.sop_instance_uid
        if image_id is None and not (s and r and o):
            raise ValueError(
                "Provide either image_id or the trio of study_instance_uid, series_instance_uid, sop_instance_uid"
            )
        return self


class CommentUpdate(BaseModel):
    """Schema for updating a comment"""
    content: str = Field(..., description="Updated comment content")


class CommentInDB(CommentBase):
    """Schema for comment in database"""
    id: int
    image_id: int
    doctor_id: Optional[int] = None
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


class CommentResponse(CommentBase):
    """Schema for comment response"""
    id: int
    image_id: int
    doctor: Optional[DoctorResponse] = None
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)
