from typing import Optional
from pydantic import BaseModel, Field
from datetime import datetime

from .doctor import DoctorResponse


class CommentBase(BaseModel):
    """Base Comment schema with common attributes"""
    content: str = Field(..., description="Comment content", example="This appears to be a fracture in the distal radius.")
    is_ai_generated: bool = Field(False, description="Whether the comment was generated by AI")
    ai_model: Optional[str] = Field(None, description="AI model used to generate the comment", example="gemini-2.0-flash")


class CommentCreate(CommentBase):
    """Schema for creating a new comment"""
    image_id: int = Field(..., description="ID of the image being commented on")


class CommentUpdate(BaseModel):
    """Schema for updating a comment"""
    content: str = Field(..., description="Updated comment content")


class CommentInDB(CommentBase):
    """Schema for comment in database"""
    id: int
    image_id: int
    doctor_id: Optional[int] = None
    created_at: datetime
    updated_at: datetime

    class Config:
        orm_mode = True


class CommentResponse(CommentBase):
    """Schema for comment response"""
    id: int
    image_id: int
    doctor: Optional[DoctorResponse] = None
    created_at: datetime
    updated_at: datetime

    class Config:
        orm_mode = True
